### PR TITLE
[Cleanup] Fixes Environment variable

### PR DESCRIPTION
**Pull request by eliasjpr**
This solves the concern around the installation of amber for a project. It will install `amber` cli globally and under the project using the amber cli shard.  If you want the `bin/amber` to be available in prod just need to move the dependency out of dev

Fixes environment variable `env` was pointing to
`Amber::Environemnt::Env` which now is simply `Environment::Env`

- Does some formatting
- Removes outdated comments
- Allows amber to be installed on `shards install` or `shards update`
- Moves `amber` cli to current project bin

Ref https://github.com/amberframework/amber/pull/946

### Workflow:

Install Amber CLI (Only)
```
brew tap amberframework/amber
brew install amber
```

Generate new project 

```
amber new {project}
cd {project}
shards install
```

Local amber cli will be added to project in `bin/amber`

```
bin/amber g scaffold ....
bin/amber db create migrate
```

#### For Production 

Move `amber_cli` out of the `development_dependencies` into `dependencies`

> This might alleviate the need of the heroku amber build pack needing to install the CLI to run migrations, this saves maintenance and reduces complexity

### CODE REVIEW

**Comment by Thellior** [comment]
When using make install the bin is generated fine. When your are generating a new project with bin/amber it works fine. When you run shards install you get a error

```shell
shards install                                                                                                                                                                                                                                               0 < 18:02:49
Fetching https://github.com/amberframework/amber.git
Fetching https://github.com/amberframework/amber-router.git
Fetching https://github.com/mosop/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/elorest/compiled_license.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/TechMagister/liquid.cr.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/amberframework/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/luckyframework/shell-table.cr.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/mosop/teeplate.git
Fetching https://github.com/amberframework/amber-cli.git
Error shard name (amber_cli) doesn't match dependency name (amber-cli)
```

**Review by Thellior — CHANGES_REQUESTED** [review]
When using make install the bin is generated fine. When your are generating a new project with bin/amber it works fine. When you run shards install you get a error

```shell
shards install                                                                                                                                                                                                                                               0 < 18:02:49
Fetching https://github.com/amberframework/amber.git
Fetching https://github.com/amberframework/amber-router.git
Fetching https://github.com/mosop/cli.git
Fetching https://github.com/mosop/optarg.git
Fetching https://github.com/mosop/callback.git
Fetching https://github.com/mosop/string_inflection.git
Fetching https://github.com/elorest/compiled_license.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/TechMagister/liquid.cr.git
Fetching https://github.com/phoffer/inflector.cr.git
Fetching https://github.com/amberframework/micrate.git
Fetching https://github.com/crystal-lang/crystal-db.git
Fetching https://github.com/crystal-lang/crystal-mysql.git
Fetching https://github.com/will/crystal-pg.git
Fetching https://github.com/stefanwille/crystal-redis.git
Fetching https://github.com/ysbaddaden/pool.git
Fetching https://github.com/luckyframework/shell-table.cr.git
Fetching https://github.com/jeromegn/slang.git
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/mosop/teeplate.git
Fetching https://github.com/amberframework/amber-cli.git
Error shard name (amber_cli) doesn't match dependency name (amber-cli)
```

**Review by Thellior — CHANGES_REQUESTED** [review]
The shards are now installing. When using the generated amber binary to generate a migration will work. When using amber watch i get an error than webpack is not installed.

```shell
../bin/amber watch                                                                                                                                                                                                                                           0 < 18:16:22
06:16:29 Watcher    | Watching 10 server files
06:16:29 Watcher    | (INFO) Building project cli-test
06:16:59 Server     | (INFO) Amber 0.9.0 serving application "Cli-test" at http://0.0.0.0:3000
06:16:59 Server     | (INFO) Server started in development.
06:16:59 Server     | (INFO) Startup Time 00:00:00.001069000
06:16:59 Watcher    | Watching 11 client files...

> cli-test@0.1.0 watch /Users/thellior/Git/amber/amber_cli/cli-test
> webpack -w --config config/webpack/development.js

sh: webpack: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cli-test@0.1.0 watch: `webpack -w --config config/webpack/development.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the cli-test@0.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thellior/.npm/_logs/2018-09-21T16_17_00_038Z-debug.log

> fsevents@1.2.4 install /Users/thellior/Git/amber/amber_cli/cli-test/node_modules/fsevents
> node install

[fsevents] Success: "/Users/thellior/Git/amber/amber_cli/cli-test/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.3 install /Users/thellior/Git/amber/amber_cli/cli-test/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/thellior/.npm/node-sass/4.9.3/darwin-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/thellior/Git/amber/amber_cli/cli-test/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.3 postinstall /Users/thellior/Git/amber/amber_cli/cli-test/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/thellior/Git/amber/amber_cli/cli-test/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
added 754 packages in 16.85s
```

Am i'm doing something incorrect with the new changes?

**Comment by Thellior** [comment]
It's only happening on the first time @eliasjpr. When running amber watch again it's working. But i think we should fix the issue that the first time it gives a error

**Comment by eliasjpr** [comment]
Live Reload dependency has been removed from CLI and now lives in its own shard `amberframework/live_reload`

**Pull request merged**
